from typing import Any

from pydantic import BaseModel, Field


class SongNode(BaseModel):
    """Flexible tree node for hierarchical song characteristics.
    
    The model generates an arbitrary tree structure based on the input,
    allowing it to organize song characteristics as it sees fit.
    """
    
    name: str = Field(description="Node label/name, e.g. 'Intro', 'Primary Instruments', 'Emotional Arc'")
    value: Any = Field(
        default=None,
        description="Optional scalar value: string, number, list, or nested structure"
    )
    children: list["SongNode"] = Field(
        default_factory=list,
        description="Child nodes forming the tree hierarchy"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional metadata attributes for this node (e.g. type, unit, confidence)"
    )


SongNode.model_rebuild()


class SongCharacteristics(BaseModel):
    """Tree-structured song characteristics generated by the model.
    
    The root contains arbitrary child nodes organized by the model based on input.
    Suitable for frontend rendering as an editable tree and conversion to markdown.
    """
    
    root: SongNode = Field(
        description="Root node containing the entire song characteristic tree"
    )

