#!/bin/bash
# Quick deployment helper for ruben-multimodal-composer.ai

DROPLET_IP="157.230.208.203"
REPO_URL="https://github.com/edavidk7/hacknation26.git"

echo "=== HackNation Quick Deploy to Droplet ==="
echo ""
echo "Droplet IP: $DROPLET_IP"
echo "Domain: ruben-multimodal-composer.ai"
echo ""
echo "Step 1: Get root password from:"
echo "  https://cloud.digitalocean.com/droplets/550236290/access"
echo ""
echo "Step 2: SSH into droplet:"
echo "  ssh root@$DROPLET_IP"
echo ""
echo "Step 3: Once logged in, run these commands:"
echo ""
echo "  # Clone repo"
echo "  cd /root"
echo "  git clone $REPO_URL"
echo "  cd hacknation26"
echo ""
echo "  # Setup environment"
echo "  cp .env.production.example .env"
echo "  nano .env  # Add your API keys"
echo ""
echo "  # Deploy!"
echo "  chmod +x deploy.sh"
echo "  ./deploy.sh"
echo ""
echo "=== Or use this one-liner after SSH ==="
echo ""
echo "cd /root && git clone $REPO_URL && cd hacknation26 && echo 'Now edit .env with: nano .env'"
